### POST request to register a new user
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "userName": "roslu",
  "password": "password"
}




### POST request to register a new user
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "userName": "Ady",
  "password": "add123",
  "firstName": "Adam",
  "lastName": "Ad",
  "email": "adam@example.com",
  "dateOfBirth": 20111002
}

### UPDATE request to update a user via his id
PUT http://localhost:8080/user/1
Content-Type: application/json

{
  "userName": "John1",
  "password": "password123",
  "firstName": "John",
  "lastName": "Joe",
  "email": "randomuser123@example.com",
  "dateOfBirth": "20111002"
}

### GET request to get all users
GET http://localhost:8080/user

### POST request to login a  user
POST http://localhost:8080/user/login
Content-Type: application/json

{
"userName": "randomUser123",
"password": "password123",
"role": "USER",
"firstName": "John",
"lastName": "Doe",
"email": "randomuser123@example.com",
"dateOfBirth": 19900101
}

### DELETE request to login a  user
DELETE http://localhost:8080/user/delete/2
Content-Type: application/json



### POST request to add a new bug
POST http://localhost:8080/bug/creation
Content-Type: application/json

{
  "bugName": "Login Issue",
  "priority": "HIGH",
  "bugDate": "2024-06-25",
  "projectName": "Bug Tracker System",
  "bugType": "Functional",
  "bugLevel": "Critical",
  "assignToDeveloper": "JohnDoe",
  "status": "Open"
}
### POST request to add a new bug
GET http://localhost:8080/bug/allBugs
Content-Type: application/json

{

}